export default {
  $headerHeight: '100rem',
  $singleSpace: '16rem',
  $doubleSpace: '32rem',
  $tripleSpace: '64rem',
  $middleSpace: '8rem',
  $smallSpace: '4rem',
  $defaultBorderRadius: '8rem',
  $borderRadiusSmall: '12.8rem',
  $borderRadiusMedium: '18rem',
  $borderRadiusLarge: '24rem',
  $missionCarouselPadding: '28rem',
  $heightButtonsAndTextInput: '52rem',
  $heightInput: '52rem',
  $carrouselImageContainerHeight: '160rem',
  $carrouselImageContainerHeightOpenMarket: '237rem',
};
